data:
  - /scratch/project_2005099/members/micheleb/projects/scaleUpMNMT/data/wmt/wmt.cs-en
  - /scratch/project_2005099/members/micheleb/projects/scaleUpMNMT/data/wmt/wmt.de-en
src_tgt:
  - cs-en
  - de-en
save_model: /scratch/project_2005099/members/micheleb/projects/scaleUpMNMT/models/train_test/MULTILINGUAL_MULTI
save_checkpoint_steps: 1000
keep_checkpoint: 1
seed: 3435
train_steps: 10000
valid_steps: 10000
warmup_steps: 800
report_every: 100

use_attention_bridge: 'true'
n_layers_attbrg: 16
layer_type_attbrg: fixed-size
attention_heads: 32

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
dec_layers: 6
enc_layers: 6
transformer_ff: 2048
heads: 8
model_type: text

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 0.001
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 2
gpu_ranks:
  - 0
  - 1
