data:
  - data/sample_data/m30k.en-de
  - data/sample_data/m30k.de-en
  - data/sample_data/m30k.de-de
  - data/sample_data/m30k.en-cs
  - data/sample_data/m30k.cs-en
  - data/sample_data/m30k.cs-cs

src_tgt:
  - en-de
  - de-en
  - de-de
  - en-cs
  - cs-en
  - cs-cs

save_model: model/demo_short/MULTILINGUAL_MULTI
save_checkpoint_steps: 25000
keep_checkpoint: 10
seed: 3435
train_steps: 200000
valid_steps: 1000000
warmup_steps: 40000
report_every: 1

use_attention_bridge: 'true'
n_layers_attbrg: 6
layer_type_attbrg: fixed-size
hidden_ab_size: 4096
attention_heads: 50
#model_dtype: fp16

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
dec_layers: 3
enc_layers: 3
transformer_ff: 2048
heads: 8
model_type: text

accum_count: 1
optim: adafactor
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 3
max_grad_norm: 0.0

batch_size: 2048
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 2
gpu_ranks:
  - 0
  - 1
